In [2]:
import pandas as pd
import numpy as np
pd.__version__

'1.0.3'

In [5]:
#one dimensional array of indexed data
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [6]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [7]:
#index is an array-like object of type pd.Index
data.index

RangeIndex(start=0, stop=4, step=1)

In [10]:
data[3]
data[0]

0.25

In [18]:
data[1:4]

1    0.50
2    0.75
3    1.00
dtype: float64

In [19]:
data = pd.Series([0.25,0.5,0.75,1.0],
                index = ['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [21]:
data['d']

1.0

In [29]:
population_dict = {'California': 38334563,
                   'Texas': 3374627542,
                   'New York': 98463664,
                   'Florida': 73642574,
                   'Illinois': 42653274}

population = pd.Series(population_dict)
population

California      38334563
Texas         3374627542
New York        98463664
Florida         73642574
Illinois        42653274
dtype: int64

In [28]:
population['California': 'Florida']

California      38334563
Texas         3374627542
New York        98463664
Florida         73642574
dtype: int64

In [33]:
pd.Series(data, index=(1,2))

1   NaN
2   NaN
dtype: float64

In [34]:
pd.Series([2,4,6])

0    2
1    4
2    6
dtype: int64

In [35]:
#data can be a scalar repeated to fill the specified index
pd.Series(5, index=[100,200,300])

100    5
200    5
300    5
dtype: int64

In [37]:
pd.Series({2: 'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [39]:
pd.Series({2: 'a', 1:'b', 3:'c'}, index=[1,2])

1    b
2    a
dtype: object

In [40]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [42]:
#construct a single 2dimensional object 
states = pd.DataFrame({'population': population, 'area': area})
states

population    area
California    38334563  423967
Texas       3374627542  695662
New York      98463664  141297
Florida       73642574  170312
Illinois      42653274  149995

In [3]:
#series as a dictionary
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                index = ['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [4]:
data['c']

0.75

In [8]:
'a' in data

True

In [9]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [10]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [11]:
data['z'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
z    1.25
dtype: float64

In [12]:
#series as one-dimensional array
#slicing by explicit index
data['a': 'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [13]:
#slicing by implicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [14]:
#masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [ ]:
#fancy indexing, this format doesn't work
#data[['a', 'e']]

In [17]:
data = pd.Series(['a', 'b', 'c'], index = [1,3,5])
data

1    a
3    b
5    c
dtype: object

In [18]:
#explicit index while indexing
data[1]

'a'

In [19]:
#implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

In [20]:
data.loc[1]

'a'

In [21]:
data.loc[1:3]

1    a
3    b
dtype: object

In [22]:
data.iloc[1]

'b'

In [23]:
data.iloc[1:3]

3    b
5    c
dtype: object

In [24]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [25]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [26]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [27]:
data.area is data['area']

True

In [29]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [30]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [31]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [32]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [34]:
data.loc[:'Florida', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860

In [36]:
#data.ix[:3, :'pop']

In [37]:
data.loc[data.density>100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [41]:
data.iloc[4,2] = 80
data

area       pop     density
California  423967        90   80.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   80.000000

In [42]:
data['Florida': 'Illinois']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   80.000000

In [43]:
data[1:3]

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [45]:
data[data.density > 100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

In [7]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0,10,4))
ser 

0    6
1    3
2    7
3    4
dtype: int64

In [8]:
df = pd.DataFrame(rng.randint(0,10,(3,4)),
                 columns = ['A', 'B','C','D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [9]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [10]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [11]:
#index alignment in series
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

In [12]:
population/area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [13]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [14]:
A = pd.Series([2,4,6], index=[0,1,2])
B = pd.Series([1,3,5], index=[1,2,3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [15]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [20]:
#index alignment in dataframe
A = pd.DataFrame(rng.randint(0,20,(2,2)),
                columns=list('AB'))
A

A   B
0  4  18
1  6   8

In [21]:
B = pd.DataFrame(rng.randint(0, 10, (3,3)),
                columns = list('BAC'))
B

B  A  C
0  6  1  3
1  8  1  9
2  8  9  4

In [22]:
A+B

A     B   C
0  5.0  24.0 NaN
1  7.0  16.0 NaN
2  NaN   NaN NaN

In [23]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0   5.0  24.0  12.0
1   7.0  16.0  18.0
2  18.0  17.0  13.0

In [24]:
#operations between Dataframe and Series
A= rng.randint(10, size=(3,4))
A

array([[1, 3, 6, 7],
       [2, 0, 3, 1],
       [7, 3, 1, 5]])

In [25]:
A - A[0]

array([[ 0,  0,  0,  0],
       [ 1, -3, -3, -6],
       [ 6,  0, -5, -2]])

In [26]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1  1 -3 -3 -6
2  6  0 -5 -2

In [27]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0 -2  0  3  4
1  2  0  3  1
2  4  0 -2  2

In [28]:
halfrow = df.iloc[0, ::2]
halfrow

Q    1
S    6
Name: 0, dtype: int64

In [29]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1  1.0 NaN -3.0 NaN
2  6.0 NaN -5.0 NaN